name       : libtasn1
version    : '4.12'
release    : 10
source     :
    - http://ftp.gnu.org/gnu/libtasn1/libtasn1-4.12.tar.gz : 6753da2e621257f33f5b051cc114d417e5206a0818fe0b1ecfd6153f70934753
homepage   : http://www.gnu.org
license    : GPL-3.0
component  : security.crypto
patterns   :
    - utils :
        - /usr/bin
        - /usr/share/man/man1
emul32     : yes
summary    : C Library that encodes and decodes DER/BER data following an ASN.1 schema
description: |
    libtasn1 is a highly portable C library that encodes and decodes DER/BER data following an ASN.1 schema.
setup      : |
    %configure --disable-static --prefix=/usr
build      : |
    %make
install    : |
    %make_install
    %make -C doc/reference install-data-local DESTDIR="$installdir"
