name       : libtasn1
version    : 4.18.0
release    : 17
source     :
    - https://ftp.gnu.org/gnu/libtasn1/libtasn1-4.18.0.tar.gz : 4365c154953563d64c67a024b607d1ee75c6db76e0d0f65709ea80a334cd1898
homepage   : https://www.gnu.org/software/libtasn1/
license    :
    - GPL-3.0-or-later
    - LGPL-2.1-or-later
component  :
    - security.crypto
    - utils : security.crypto
patterns   :
    - utils :
        - /usr/bin
        - /usr/share/man/man1
emul32     : yes
summary    : C Library that encodes and decodes DER/BER data following an ASN.1 schema
description: |
    libtasn1 is a highly portable C library that encodes and decodes DER/BER data following an ASN.1 schema.
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
    %make -C doc/reference install-data-local DESTDIR="$installdir"
check      : |
    %make check
