name       : libtasn1
version    : '4.10'
release    : 9
source     :
    - http://ftp.gnu.org/gnu/libtasn1/libtasn1-4.10.tar.gz : 681a4d9a0d259f2125713f2e5766c5809f151b3a1392fd91390f780b4b8f5a02
homepage   : http://www.gnu.org
license    : GPL-3.0
component  : security.crypto
patterns   :
    - utils :
        - /usr/bin
        - /usr/share/man/man1
emul32     : yes
summary    : C Library that encodes and decodes DER/BER data following an ASN.1 schema
description: |
    libtasn1 is a highly portable C library that encodes and decodes DER/BER data following an ASN.1 schema.
setup      : |
    %configure --disable-static --prefix=/usr
build      : |
    %make
install    : |
    %make_install
    %make -C doc/reference install-data-local DESTDIR="$installdir"
