name        : libtasn1
version     : 4.7
release     : 6
source      :
    - http://ftp.gnu.org/gnu/libtasn1/libtasn1-4.7.tar.gz : a40780dc93fc6d819170240e8ece25352058a85fd1d2347ce0f143667d8f11c9
homepage    : http://www.gnu.org
license     :
    - GPL-3.0
builddeps   :
    - glibc-32bit-devel
    - libgcc-32bit
patterns    :
    - utils:
        - /usr/bin
        - /usr/share/man/man1
summary     : C Library that encodes and decodes DER/BER data following an ASN.1 schema
description : |
    libtasn1 is a highly portable C library that encodes and decodes DER/BER data following an ASN.1 schema.
setup      : |
    %configure --disable-static --prefix=/usr
build      : |
    %make
install    : |
    %make_install
    %make -C doc/reference install-data-local DESTDIR="$installdir"
