name       : libtasn1
version    : 4.17.0
release    : 15
source     :
    - https://ftp.gnu.org/gnu/libtasn1/libtasn1-4.17.0.tar.gz : ece7551cea7922b8e10d7ebc70bc2248d1fdd73351646a2d6a8d68a9421c45a5
homepage   : https://www.gnu.org/software/libtasn1/
license    :
    - GPL-3.0-or-later
    - LGPL-2.1-or-later
component  : security.crypto
patterns   :
    - utils :
        - /usr/bin
        - /usr/share/man/man1
emul32     : yes
summary    : C Library that encodes and decodes DER/BER data following an ASN.1 schema
description: |
    libtasn1 is a highly portable C library that encodes and decodes DER/BER data following an ASN.1 schema.
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
    %make -C doc/reference install-data-local DESTDIR="$installdir"
check      : |
    %make check
