name       : libtasn1
version    : '4.14'
release    : 13
source     :
    - https://ftp.gnu.org/gnu/libtasn1/libtasn1-4.14.tar.gz : 9e604ba5c5c8ea403487695c2e407405820d98540d9de884d6e844f9a9c5ba08
homepage   : https://www.gnu.org/software/libtasn1/
license    :
    - GPL-3.0-or-later
    - LGPL-2.1-or-later
component  : security.crypto
patterns   :
    - utils :
        - /usr/bin
        - /usr/share/man/man1
emul32     : yes
summary    : C Library that encodes and decodes DER/BER data following an ASN.1 schema
description: |
    libtasn1 is a highly portable C library that encodes and decodes DER/BER data following an ASN.1 schema.
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
    %make -C doc/reference install-data-local DESTDIR="$installdir"
check      : |
    %make check
