name       : libtasn1
version    : 4.19.0
release    : 18
source     :
    - https://ftp.gnu.org/gnu/libtasn1/libtasn1-4.19.0.tar.gz : 1613f0ac1cf484d6ec0ce3b8c06d56263cc7242f1c23b30d82d23de345a63f7a
homepage   : https://www.gnu.org/software/libtasn1/
license    :
    - GPL-3.0-or-later
    - LGPL-2.1-or-later
component  :
    - security.crypto
    - utils : security.crypto
summary    : C Library that encodes and decodes DER/BER data following an ASN.1 schema
description: |
    libtasn1 is a highly portable C library that encodes and decodes DER/BER data following an ASN.1 schema.
patterns   :
    - utils :
        - /usr/bin
        - /usr/share/man/man1
emul32     : yes
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
    %make -C doc/reference install-data-local DESTDIR="$installdir"
check      : |
    %make check
